doctrine:
    dbal:
        default_connection: customers
        connections:
            customers:
                driver: 'pdo_mysql'
                host: '%env(resolve:DATABASE_HOST_CUSTOMERS)%'
                port: '%env(resolve:DATABASE_PORT_CUSTOMERS)%'
                dbname: '%env(resolve:DATABASE_NAME_CUSTOMERS)%'
                user: '%env(resolve:DATABASE_USER_CUSTOMERS)%'
                password: '%env(resolve:DATABASE_PASSWORD_CUSTOMERS)%'
                charset: utf8mb4
            payments:
                driver: 'pdo_mysql'
                host: '%env(resolve:DATABASE_HOST_PAYMENTS)%'
                port: '%env(resolve:DATABASE_PORT_PAYMENTS)%'
                dbname: '%env(resolve:DATABASE_NAME_PAYMENTS)%'
                user: '%env(resolve:DATABASE_USER_PAYMENTS)%'
                password: '%env(resolve:DATABASE_PASSWORD_PAYMENTS)%'
                charset: utf8
            products:
                driver: 'pdo_mysql'
                host: '%env(resolve:DATABASE_HOST_PRODUCTS)%'
                port: '%env(resolve:DATABASE_PORT_PRODUCTS)%'
                dbname: '%env(resolve:DATABASE_NAME_PRODUCTS)%'
                user: '%env(resolve:DATABASE_USER_PRODUCTS)%'
                password: '%env(resolve:DATABASE_PASSWORD_PRODUCTS)%'
                charset: utf8
            carts:
                driver: 'pdo_mysql'
                host: '%env(resolve:DATABASE_HOST_CARTS)%'
                port: '%env(resolve:DATABASE_PORT_CARTS)%'
                dbname: '%env(resolve:DATABASE_NAME_CARTS)%'
                user: '%env(resolve:DATABASE_USER_CARTS)%'
                password: '%env(resolve:DATABASE_PASSWORD_CARTS)%'
                charset: utf8
        types:
            uuid: Shared\Infrastructure\Doctrine\Mapping\UuidType
            customer_id: Customer\Infrastructure\Doctrine\Mapping\CustomerIdType
            review_id: Customer\Infrastructure\Doctrine\Mapping\ReviewIdType
            product_id: Shared\Infrastructure\Doctrine\Mapping\ProductIdType
            cart_id: Cart\Infrastructure\Doctrine\Mapping\CartIdType
            cart_item_id: Cart\Infrastructure\Doctrine\Mapping\CartItemIdType
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: customers_em
        entity_managers:
            customers_em:
                connection: customers
                mappings:
                    Shared\Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Mapping'
                        prefix: 'Shared\Domain'
                    Customer\Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Customer/Infrastructure/Doctrine/Mapping'
                        prefix: 'Customer\Domain'
            payments_em:
                connection: payments
                mappings:
                    Shared\Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Mapping'
                        prefix: 'Shared\Domain'
                    Payment\Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Payment/Infrastructure/Doctrine/Mapping'
                        prefix: 'Payment\Domain'
            products_em:
                connection: products
                mappings:
                    Shared\Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Mapping'
                        prefix: 'Shared\Domain'
                    Product\Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Product/Infrastructure/Doctrine/Mapping'
                        prefix: 'Product\Domain'

            carts_em:
                connection: carts
                mappings:
                    Shared\Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Shared/Infrastructure/Doctrine/Mapping'
                        prefix: 'Shared\Domain'
                    Cart\Domain:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Cart/Infrastructure/Doctrine/Mapping'
                        prefix: 'Cart\Domain'