create_product:
  path: '/products'
  controller: Product\Infrastructure\Controller\CreateProductPOSTController
  methods: [ POST ]

find_products:
  path: '/products'
  controller: Product\Infrastructure\Controller\FindProductsGETController
  methods: [ GET ]

find_product_by_id:
  path: '/products/{id}'
  controller: Product\Infrastructure\Controller\FindProductByIdGETController
  methods: [ GET ]