parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    Shared\:
        resource: '../src/Shared/'
    Customer\:
        resource: '../src/Customer/'
    Payment\:
        resource: '../src/Payment/'
    Product\:
        resource: '../src/Product/'
    Cart\:
        resource: '../src/Cart/'
