parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    Shared\:
        resource: '../libs/shared/'
    Customer\:
        resource: '../apps/customer/src/'
    Payment\:
        resource: '../apps/payment/src/'
    Product\:
        resource: '../apps/product/src/'
    Cart\:
        resource: '../apps/cart/src/'
    User\:
        resource: '../apps/user/src/'