create_cart:
  path: '/carts'
  controller: Cart\Infrastructure\Controller\CreateCartPOSTController
  methods: [ POST ]

find_carts:
  path: '/carts'
  controller: Cart\Infrastructure\Controller\FindCartsGETController
  methods: [ GET ]